"""Like asdada

Revision ID: 012c90ac580f
Revises: 1b912fa6ab36
Create Date: 2023-07-15 11:30:46.428576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '012c90ac580f'
down_revision = '1b912fa6ab36'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
