"""empty message

Revision ID: 0326e928ea56
Revises: fd35e1cfe9a2
Create Date: 2023-07-10 14:37:41.734397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0326e928ea56'
down_revision = 'fd35e1cfe9a2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('post',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('head', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('edit_at', sa.TIMESTAMP(), nullable=True),
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('user', sa.Column('user_id', sa.UUID(), nullable=True))
    op.add_column('user', sa.Column('post_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'user', 'post', ['post_id'], ['id'])
    op.create_foreign_key(None, 'user', 'user', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.drop_column('user', 'post_id')
    op.drop_column('user', 'user_id')
    op.drop_table('post')
    # ### end Alembic commands ###
