"""Like

Revision ID: 0e9b8ebfa0d7
Revises: 1687ed047815
Create Date: 2023-07-13 15:11:07.664587

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '0e9b8ebfa0d7'
down_revision = '1687ed047815'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
