"""empty message

Revision ID: 1645766887f8
Revises: 0326e928ea56
Create Date: 2023-07-10 14:44:23.441921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1645766887f8'
down_revision = '0326e928ea56'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
