"""Like

Revision ID: 1687ed047815
Revises: ff9e0ecb7ec9
Create Date: 2023-07-13 15:11:02.379074

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1687ed047815'
down_revision = 'ff9e0ecb7ec9'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
