"""Like ddd

Revision ID: 1698324b198b
Revises: 4cb100078d55
Create Date: 2023-07-13 15:13:34.095015

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1698324b198b'
down_revision = '4cb100078d55'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
