"""Like ddd

Revision ID: 1b912fa6ab36
Revises: 9159d8339763
Create Date: 2023-07-15 11:28:10.824041

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1b912fa6ab36'
down_revision = '9159d8339763'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
