"""empty message

Revision ID: 1dcf0afc238b
Revises: 9bfd26901afd
Create Date: 2023-07-09 18:02:19.720244

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1dcf0afc238b'
down_revision = '9bfd26901afd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
