"""Like

Revision ID: 4b7f96e760aa
Revises: 6a61a7b86afd
Create Date: 2023-07-13 15:12:55.844734

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4b7f96e760aa'
down_revision = '6a61a7b86afd'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
