"""Like

Revision ID: 4cb100078d55
Revises: 4b7f96e760aa
Create Date: 2023-07-13 15:13:21.790486

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4cb100078d55'
down_revision = '4b7f96e760aa'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
