"""Like relate1difhjsif

Revision ID: 5e66ca421d5c
Revises: fa340e312ba0
Create Date: 2023-07-15 11:36:49.481620

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5e66ca421d5c'
down_revision = 'fa340e312ba0'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
