"""empty message

Revision ID: 666aaeef843d
Revises: 704390859d7d
Create Date: 2023-07-09 20:18:16.401202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '666aaeef843d'
down_revision = '704390859d7d'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
