"""Like

Revision ID: 6a61a7b86afd
Revises: 0e9b8ebfa0d7
Create Date: 2023-07-13 15:12:50.206358

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6a61a7b86afd'
down_revision = '0e9b8ebfa0d7'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
