"""empty message

Revision ID: 704390859d7d
Revises: 8d839c7de288
Create Date: 2023-07-09 20:17:53.321201

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '704390859d7d'
down_revision = '8d839c7de288'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
