"""Like relate1

Revision ID: 80999a8174b2
Revises: a5e4e3c64c0a
Create Date: 2023-07-15 11:35:52.366415

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '80999a8174b2'
down_revision = 'a5e4e3c64c0a'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
