"""empty message

Revision ID: 8d839c7de288
Revises: ff47b9e81102
Create Date: 2023-07-09 20:09:26.534230

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8d839c7de288'
down_revision = 'ff47b9e81102'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
