"""empty message

Revision ID: 9bfdcfb052df
Revises: dc9677c4599e
Create Date: 2023-07-10 13:34:15.380583

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9bfdcfb052df'
down_revision = 'dc9677c4599e'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
