"""Like relate1difh

Revision ID: a24f7d5b51bd
Revises: 5e66ca421d5c
Create Date: 2023-07-15 11:40:03.760479

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a24f7d5b51bd'
down_revision = '5e66ca421d5c'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
