"""Like relate

Revision ID: a5e4e3c64c0a
Revises: 012c90ac580f
Create Date: 2023-07-15 11:34:41.746532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a5e4e3c64c0a'
down_revision = '012c90ac580f'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
