"""empty message

Revision ID: c5ca103f2765
Revises: 9bfdcfb052df
Create Date: 2023-07-10 13:35:46.575965

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5ca103f2765'
down_revision = '9bfdcfb052df'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
