"""empty message

Revision ID: dc9677c4599e
Revises: 8ccc68f08038
Create Date: 2023-07-10 13:32:53.492397

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dc9677c4599e'
down_revision = '8ccc68f08038'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
