"""Like relate1

Revision ID: fa340e312ba0
Revises: 80999a8174b2
Create Date: 2023-07-15 11:36:43.904447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa340e312ba0'
down_revision = '80999a8174b2'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
