"""empty message

Revision ID: ff47b9e81102
Revises: 1dcf0afc238b
Create Date: 2023-07-09 20:08:49.567675

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff47b9e81102'
down_revision = '1dcf0afc238b'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
